name: frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0	
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
