services:
  fastapi:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - POETRY_VERSION=1.8.1
      - POETRY_VIRTUALENVS_CREATE=false
      - POETRY_NO_INTERACTION=1
      - POETRY_HOME="/opt/poetry"

