services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - POETRY_VERSION=1.8.1
      - POETRY_VIRTUALENVS_CREATE=false
      - POETRY_NO_INTERACTION=1
      - POETRY_HOME="/opt/poetry"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s  
      retries: 5
    labels:
      autoheal-app: true

  autoheal:
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
