services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - POETRY_VERSION=1.8.1
      - POETRY_VIRTUALENVS_CREATE=false
      - POETRY_NO_INTERACTION=1
      - POETRY_HOME="/opt/poetry"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s  # Increased from 10s to 15s
      timeout: 10s   # Increased from 5s to 10s
      retries: 10    # Increased from 5 to 10