// Mocks generated by Mockito 5.4.4 from annotations
// in frontend/test/src/features/authentication/presentation/log_in_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/src/features/authentication/application/member_service.dart'
    as _i4;
import 'package:frontend/src/features/authentication/domain/member.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMember_0 extends _i1.SmartFake implements _i2.Member {
  _FakeMember_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_1 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MemberService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberService extends _i1.Mock implements _i4.MemberService {
  MockMemberService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Member> getMember() => (super.noSuchMethod(
        Invocation.method(
          #getMember,
          [],
        ),
        returnValue: _i5.Future<_i2.Member>.value(_FakeMember_0(
          this,
          Invocation.method(
            #getMember,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Member>);

  @override
  _i5.Future<_i3.AuthResponse> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_1(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  String getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<String> getJWT() => (super.noSuchMethod(
        Invocation.method(
          #getJWT,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getJWT,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> getUsername() => (super.noSuchMethod(
        Invocation.method(
          #getUsername,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getUsername,
            [],
          ),
        )),
      ) as _i5.Future<String>);
}
