import 'package:supabase_flutter/supabase_flutter.dart';

/// LoginResponse model, this model is not autogenerated because supabase integration with flutter.
class LoginResponse {
    /// The token to be used for authentication.
    final User user;

    /// The user id.
    final Session session;

    LoginResponse({
        required this.user,
        required this.session,
    });
}