name: CI

on:
  push:
    paths: 
      - 'api/**'
      - '.github/workflows/integrate.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker build
      run: docker build -t api-image ./api

    - name: Run Docker container in detached mode
      run: |
        echo "Running the Docker container (api-container) in detached mode..."
        docker run -d --name api-container -p 8000:8000 api-image # Use custom container and image name
      shell: bash

    - name: Wait for container health check
      run: |
        echo "Waiting for the API service to become healthy..."
        for i in {1..10}; do
          STATUS=$(docker inspect -f '{{.State.Health.Status}}' api-container) # Inspect custom container name
          if [ "$STATUS" == "healthy" ]; then
            echo "API service is healthy!"
            break
          elif [ "$STATUS" == "unhealthy" ]; then
            echo "API service failed to become healthy. Checking logs..."
            docker logs api-container # Logs from custom container
            exit 1
          fi
          if [ "$i" -eq 10 ]; then
            echo "API service failed to become healthy in time."
            docker logs api-container # Logs from custom container
            exit 1
          fi
          echo "API service not healthy yet... retrying in 5 seconds"
          sleep 5
        done

    - name: Run tests
      run: |
        echo "Running health check on the API service..."
        curl -f http://localhost:8000/health || exit 1

    - name: Tear down services
      if: always()
      run: |
        echo "Cleaning up..."
        docker stop api-container || true # Stop custom container
        docker rm api-container || true   # Remove custom container
