name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run Docker Compose services
      run: docker compose up -d

    - name: Check Docker containers
      run: docker compose ps  # Check if the containers are up and running

    - name: Wait for health checks
      run: sleep 5

    - name: Show logs
      run: docker compose logs

    - name: Run tests
      run:  curl -f http://localhost:8000/health || exit 1

    - name: Tear down services
      if: always()
      run: docker compose down

    - name: Capture API service logs on failure
      if: failure()
      run: docker compose logs api  # Always capture logs on failure
